### ISSUE TITLE
Write error when saving Pinball Dreams to disk

### ISSUE THREAD

**Issue by MarkWllms** [pelrun/dsk2cdt2disc#14]
When I create a tape image for [Pinball Dreams](http://bg-games.com/wp-content/uploads/2019/10/PinballDreamsCPC.zip), the resulting tape causes a write error on track 2. A similar problem occurs on both sides of the disk. I have reproduced this problem in an emulator for the screenshot attached, to demonstrate that it is not an issue with my physical disk or drive. I am using version 2020.2
![Disc_Error](https://user-images.githubusercontent.com/25341742/99195991-52e5fa00-2781-11eb-96da-88888aac91e3.png)

**Comment by pelrun** [comment]
```
Track: 0 Side: 0 Sectors: c1 c6 c2 c7 c3 c8 c4 c9 c5
Track: 1 Side: 0 Sectors: c1 c6 c2 c7 c3 c8 c4 c9 c5
Track: 2 Side: 0 Sectors: 01 02 03 04 05 06 07 08 09 0a
Track: 3 Side: 0 Sectors: 03 04 05 06 07 08 09 0a 01 02
Track: 4 Side: 0 Sectors: 05 06 07 08 09 0a 01 02 03 04
Track: 5 Side: 0 Sectors: 07 08 09 0a 01 02 03 04 05 06
Track: 6 Side: 0 Sectors: 09 0a 01 02 03 04 05 06 07 08
Track: 7 Side: 0 Sectors: 01 02 03 04 05 06 07 08 09 0a
Track: 8 Side: 0 Sectors: 03 04 05 06 07 08 09 0a 01 02
Track: 9 Side: 0 Sectors: 05 06 07 08 09 0a 01 02 03 04
Track: 10 Side: 0 Sectors: 07 08 09 0a 01 02 03 04 05 06
Track: 11 Side: 0 Sectors: 09 0a 01 02 03 04 05 06 07 08
Track: 12 Side: 0 Sectors: 01 02 03 04 05 06 07 08 09 0a
Track: 13 Side: 0 Sectors: 03 04 05 06 07 08 09 0a 01 02
Track: 14 Side: 0 Sectors: 05 06 07 08 09 0a 01 02 03 04
Track: 15 Side: 0 Sectors: 07 08 09 0a 01 02 03 04 05 06
Track: 16 Side: 0 Sectors: 09 0a 01 02 03 04 05 06 07 08
Track: 17 Side: 0 Sectors: 01 02 03 04 05 06 07 08 09 0a
Track: 18 Side: 0 Sectors: 03 04 05 06 07 08 09 0a 01 02
Track: 19 Side: 0 Sectors: 05 06 07 08 09 0a 01 02 03 04
```

As expected, it's a funny format, so I'm either parsing it badly or it's one of the ones that can't easily be written by the CPC. Will poke at it more when I get the chance.

**Comment by pelrun** [comment]
Looks like I'm not setting GAP#3 correctly. That should be a fairly easy fix.

**Comment by pelrun** [comment]
I've uploaded a new v2020.3 release, see if that works.

**Comment by MarkWllms** [comment]
I've downloaded the new version, but get the same write fail under winape.

**Comment by pelrun** [comment]
Oh phooey. I've pulled the release and I'll try again.

**Comment by MarkWllms** [comment]
Is this an issue with 10 sectors per track? There are normally 9, but I don't know what the real or virtual drive is capable of writing.
Or is it that the first 2 tracks have the normal 9 sectors, but the subsequent data tracks have 10.
It seems significant that the write fail occurs when the number of sectors changes. Does the code expect the the number of sectors per track to remain constant?
I am taking my information from https://www.seasip.info/Cpm/amsform.html

**Comment by pelrun** [comment]
It's the gap between the sectors that has to be reduced in order to fit the extra sector in. And it turns out there are two places in the XDPB that need to be changed to do that - my first attempt only did one of them.

**Comment by MarkWllms** [comment]
I've compared the 2 tracks written by v2020.2 (before the write fail) with the original disk image (side B).
Track 0 is identical apart from the wrong GAP3 - the original has GAP3 of 2A, the copy has 4E. 9 sectors, C1-C9.
Track 1 appears different. Same wrong GAP3, but where the original has 9 sectors C1-C9 again, the copy has 10 sectors 01-0A. The contents of both tracks are 'blank' (E5 repeated). The track ID also shows as 2, instead of 1.
![Track 1](https://user-images.githubusercontent.com/25341742/99808537-ed0ac100-2b38-11eb-9250-f36e82cd761c.png)

This sector layout is the same as track 2 of the original, so it might just be that the failed attempt to write Track 2 has just overwritten the track layout of Track 1 (without changing its contents).
All done using WinAPE.

**Comment by pelrun** [comment]
I don't know what's happening there, but I think it's just a WinApe issue. In any case my most recent fixes do work, I simply haven't had the chance to test it on WinApe or hardware until now (I'm usually using CPCEC which doesn't fully emulate gap#3) so I hadn't built a new windows release. It's up now, v2020.4.

**Comment by MarkWllms** [comment]
Definitely working now on real hardware. Maybe the WinApe error was a distraction. Sorry if it was.
