### ISSUE TITLE
Read error handling

### ISSUE THREAD

**Issue by pelrun** [pelrun/dsk2cdt2disc#3]
If CALLBCA1 fails with a read error, it isn't being passed back to BASIC and exomizer then crashes the machine.

Return CALLBCA1's return value in another parameter and handle as appropriate.

**Comment by cpcitor** [comment]
Hello. Was it fixed in 675f95b3a357b51b63fe5a79f41d9a929500eb3e labeled "Bugfixes" ?
That commit changes a number of lines, several independent commits with an explanation line each time would have been more readable.

**Comment by pelrun** [comment]
Beyond the print line changes, this fix is the ONLY thing in that commit. So how exactly should it have been split apart?

**Comment by cpcitor** [comment]
Actual issue (not fully reporting read errors) still not fully closed. At BASIC line 220, `ret` value is still not checked.
