### ISSUE TITLE
Build instructions fail to mention dependency `z80-unknown-coff-as`.

### ISSUE THREAD

**Issue by cpcitor** [pelrun/dsk2cdt2disc#7]
src/readme.txt reads:

> Download exomizer and 2cdt and extract somewhere
> Edit Makefile and change EXOMIZER_PATH and 2CDT_PATH
> to point to the appropriate directories

This is insufficient. Makefile assumes availability of a Z80 assembler named `z80-unknown-coff-as`.

```
z80-unknown-coff-as ./dsk2cdt-src/rsx.s -o rsx.o
make: z80-unknown-coff-as: Command not found
Makefile:26: recipe for target 'rsx.bin' failed
make: *** [rsx.bin] Error 127
make: Target 'dsk2cdt' not remade because of errors.
```

This is locally fixed on Debian and Ubuntu by installing package `z80-binutils`.

This very bug can be fixed by updating the build instructions.

**Comment by pelrun** [comment]
Latest commit has updated the build instructions.

**Comment by cpcitor** [comment]
Indeed commit 213832aa4855069660304c779f458b8d8a4a79dc. Thanks.
