### ISSUE TITLE
Build fails because makefile does not link opth.o.

### ISSUE THREAD

**Issue by cpcitor** [pelrun/dsk2cdt2disc#8]
Build fails with this error:

```
cdt.o: In function `SetTZXBlockWriteMethodOptionHandler':
.../dsk2cdt2disc/src/./2cdt/src/2cdt.c:940: undefined reference to `ArgumentList_GetNext'
cdt.o: In function `SetDataMethodOptionHandler':
.../dsk2cdt2disc/src/./2cdt/src/2cdt.c:983: undefined reference to `ArgumentList_GetNext'
cdt.o: In function `SetFileTypeOptionHandler':
.../dsk2cdt2disc/src/./2cdt/src/2cdt.c:997: undefined reference to `ArgumentList_GetNext'
cdt.o: In function `SpecifySpeedWriteOptionHandler':
.../dsk2cdt2disc/src/./2cdt/src/2cdt.c:903: undefined reference to `ArgumentList_GetNext'
cdt.o: In function `SetInitialPauseOptionHandler':
.../dsk2cdt2disc/src/./2cdt/src/2cdt.c:966: undefined reference to `ArgumentList_GetNext'
cdt.o:.../dsk2cdt2disc/src/./2cdt/src/2cdt.c:1042: more undefined references to `ArgumentList_GetNext' follow
cdt.o: In function `main_2cdt':
.../dsk2cdt2disc/src/./2cdt/src/2cdt.c:1112: undefined reference to `ArgumentList_Execute'
collect2: error: ld returned 1 exit status
Makefile:20: recipe for target 'dsk2cdt' failed
make: *** [dsk2cdt] Error 1
```

`ArgumentList_GetNext` and `ArgumentList_Execute' are part of `2cdt` and compiled to `opth.o`.

Will offer pull request.

**Comment by pelrun** [comment]
Unfortunately 2cdt can't be built as a library and I didn't want to maintain a fork. So, when something changes in the 2cdt build setup, this sort of fix is needed.

Did I mention I wrote this tool mostly as a joke? :)

**Comment by cpcitor** [comment]
This tool, if it works, is much better than a joke, but a clever hack. Here I have a CPC but the few discs I have I can't read them reliably and thus I can't format any (CPC need to how run a formatting tool, from a disc, how do I get a formatting tool without a working disc ?). 

You actually made an interesting bootstraping tool, an alternative to plugging a 3.5-inch drive with the power supply need, etc. A PC and an audio cable is enough. That's what I expect, so much more value than a joke. :-)

It can also be used when cross-building programs that actually need a floppy disk (vs programs that work perfectly well with a pure cassette-style workflow).

**Comment by pelrun** [comment]
Oh, I know. That's why I said "mostly" :)
